# Generated by Django 6.0.6 on 2026-06-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0004_alter_property_title_alter_property_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(to='rent_app.amenity'),
        ),
    ]
